package-lock.json, package.json, src/components/ui/connectWallet.tsx, src/constants/index.ts, src/state/connectedWallet.ts
=> Add wallet connection

src/app/page.tsx, src/components/animations/starfield.tsx, src/components/ui/navbar.tsx, tailwind.config.ts
- Closes #11 
- Adds an animation for the landing page.
https://github.com/user-attachments/assets/767aba83-e6ab-4977-b9be-6b29f4d81cdf
=> [feat] addding starfield animation

package-lock.json, package.json, src/app/hooks/usePositions.ts, src/app/mypositions/page.tsx, src/components/ui/footer.tsx, src/types/Position.ts
- Closes #16 
- Adding table and interface to display user positions + minor fixes + positions hook base.
- Current output:
=> #16 setup for positions fetching

package-lock.json, package.json, src/abis/EkuboCore.ts, src/apis/chainLink.ts, src/apis/ekuboApi.ts, src/app/calculators/ekubo/page.tsx, src/app/calculators/page.tsx, src/app/globals.css, src/app/mypositions/page.tsx, src/app/page.tsx, src/components/ui/Calculator.tsx, src/components/ui/modals/ErrorModal.tsx, src/components/ui/navbar.tsx, src/constants/index.ts, src/types/Pool.ts, src/types/PoolState.ts, src/utils/index.ts, tailwind.config.ts
- Closes #19 
- Current output:
=> #19 adding fee calculation logic

package-lock.json, src/apis/ekuboApi.ts, src/app/calculators/ekubo/page.tsx, src/app/page.tsx, src/components/ui/Calculator.tsx, src/utils/index.ts
- Closes #21 
- This PR will let the calculator to fetch the liquidity for a price range.
- TODO: verify we are getting the correct liquidity amount.
=> #21 fetching liquidity in range function

package-lock.json, src/app/layout.tsx, src/components/ui/modals/ChatWidget.tsx
- Closes #31 
- Current output:
https://github.com/user-attachments/assets/53680e42-8c4f-44ec-872a-4f6e8024c95d
=> #31 Adding chat design

src/app/knowmore/page.tsx
=> #29 [feat] Implement "Know More" New Design

package-lock.json, src/components/ui/modals/ChatWidget.tsx, src/types/Message.ts
- Closes #37 
- Current Output:
https://github.com/user-attachments/assets/66af3685-814d-40b8-b86d-4aec728c7370
=> #37 implementing Lumos AI agent

package-lock.json, package.json, src/apis/ekuboApi.ts, src/app/calculators/ekubo/page.tsx, src/app/mypositions/page.tsx, src/components/ui/LoadingSpinner.tsx
=> #32 implement loading spinner

src/app/calculators/ekubo/page.tsx, src/components/ui/Calculator.tsx
=> #42 implement token amounts calculations

.github/pull_request_template.md
=> #36 [docs] Setup a Pull Request (PR) Template

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/onlydust_issue_template.md
_Provide a detailed description of the changes made in this PR. Explain why these changes are necessary and what problems they solve._  
- **Changes made:**
=> #46 [docs] Add Issue Templates for Lumos Repository

package-lock.json, src/apis/chainLink.ts, src/apis/ekuboApi.ts, src/app/calculators/ekubo/page.tsx, src/components/ui/Calculator.tsx, src/lib/utils.ts
- **Future TODOs (if any):**  
- Get the volume percentage of the total volume.
- Ensure we are getting the liquidity right.
=> #48 Fetch price from different source

eslint.config.mjs, package-lock.json, package.json, src/apis/ekuboApi.ts, src/apis/pragma.ts, src/app/calculators/ekubo/page.tsx, src/app/calculators/page.tsx, src/app/mypositions/page.tsx, src/components/ui/Calculator.tsx, src/components/ui/modals/TokenSelector.tsx, src/lib/utils.ts
=> #52 Adjusting the app to deploy the prototype

src/apis/ekuboApi.ts, src/lib/utils.ts
Assert the virtual liquidity provided by the user is correctly calculated
=> #56 correctly fetching liquidity

src/app/calculators/ekubo/page.tsx, src/app/calculators/page.tsx, src/components/ui/Calculator.tsx, src/components/ui/calculatorCard.tsx
=> #58 general UI fixes

package-lock.json, src/apis/ekuboApi.ts, src/app/calculators/ekubo/page.tsx, src/app/layout.tsx, src/components/ui/Calculator.tsx, src/lib/utils.ts
Validate token amounts on UI are correct
=> #60 calculating liquidity according to uniswap v3 whitepaper

package-lock.json, src/components/ui/Calculator.tsx, src/components/ui/modals/ChatWidget.tsx, src/lib/utils.ts
Using correct formulas to calculate liquidity provided by the user.
Assert we are calculating token amounts correctly (this will involve studying a lot xd)
=> #60 correctly calculating delta liquidity

package-lock.json, src/apis/ekuboApi.ts, src/app/calculators/ekubo/page.tsx, src/app/knowmore/page.tsx, src/app/mypositions/page.tsx, src/components/ui/Calculator.tsx, src/types/Position.ts
=> #69 token0/token1 refactor

next.config.ts, src/apis/pragma.ts, src/components/ui/modals/LoginModal.tsx
=> #75 login and register updates + minor UI fixes

src/components/ui/Calculator.tsx, src/lib/utils.ts
=> #77 fix token deposit amounts calculation

.env.example, next.config.ts, package-lock.json, src/components/ui/modals/ChatWidget.tsx
=> #79 setup lumos agent

next.config.ts, src/apis/ekuboApi.ts, src/app/calculators/ekubo/page.tsx, src/app/pools/page.tsx, src/components/ui/Calculator.tsx, src/lib/cache/tokenPriceCache.ts
- Calculate APY
- Calculate price volatility
- Implement export to csv feature
- Implement favorite pools
=> #83 fetching pools

package-lock.json, src/apis/lumosApi.ts, src/app/layout.tsx, src/app/page.tsx, src/components/ui/modals/LoginModal.tsx, src/components/ui/navbar.tsx
=> #86 adding hamburger menu

src/components/ui/modals/LoginModal.tsx
=> #90 Fix on save user, backend changes

src/app/pricing/checkout/page.tsx
=> #93 adding suspense wrap on checkout

src/app/pricing/checkout/page.tsx
=> #93 wrap checkout in suspense

src/app/api/lumos/users/route.ts, src/app/pools/page.tsx
_Provide a detailed description of the changes made in this PR. Explain why these changes are necessary and what problems they solve._  
- **Changes made:**  
aptura de pantalla 2025-03-10 a la(s) 12 21 40 p  m" src="https://github.com/user-attachments
=> #87 Save User Favorite Pools

src/app/api/ekuboApi.ts, src/app/api/lumos/users/route.ts, src/app/pools/page.tsx, src/app/pricing/checkout/page.tsx, src/constants/index.ts, src/lib/utils.ts, src/types/EkuboPoolsDisplay.ts
=> #108 fix fav pools

src/app/page.tsx
=> #113 new landing page design

package-lock.json, src/app/api/ekuboApi.ts, src/app/calculators/ekubo/page.tsx, src/app/calculators/haiko/page.tsx, src/app/page.tsx, src/components/ui/Calculator.tsx, src/components/ui/modals/ILCalculator.tsx
=> #41 IL calculator BETA

package-lock.json, package.json, src/app/globals.css, src/app/layout.tsx, src/components/ui/footer.tsx
=> #118 hotfix

src/app/api/ekuboApi.ts, src/app/calculators/haiko/page.tsx, src/app/page.tsx, src/components/ui/Calculator.tsx, src/components/ui/footer.tsx, src/components/ui/modals/ILCalculator.tsx
=> fix fee calculation

src/app/calculators/ekubo/page.tsx
_Provide a detailed description of the changes made in this PR. Explain why these changes are necessary and what problems they solve._  
- **Changes made:**
=> #134 Validate selected fee pre ekubo calculator

src/app/api/lumos/positions/route.ts, src/components/ui/modals/CreateVesuPosition.tsx, src/types/PositionDB.ts
_Provide a detailed description of the changes made in this PR. Explain why these changes are necessary and what problems they solve._  
- **Changes made:**
=> #144 Store positions in db
